version: '3.8'

services:
  auth:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: auth-server
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/service-account-key.json
    networks:
      - auth-network
      - /app/.next
    depends_on:
      - server
    networks:
      - landing-network
    command: npm run dev

volumes:
networks:
  auth-network:
    driver: bridge
