version: '3.8'

services:
  auth:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: auth-server-prod
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/service-account-key.json:ro
    networks:
      - auth-network
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    depends_on:
      - server
    networks:
    networks:
      - auth-network
